// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import Attitude3dController from "controllers/attitude_3d_controller"
application.register("attitude-3d", Attitude3dController)

import AutoRefreshController from "controllers/auto_refresh_controller"
application.register("auto-refresh", AutoRefreshController)

import CanvasThemeController from "controllers/canvas_theme_controller"
application.register("canvas-theme", CanvasThemeController)

import ClipboardController from "controllers/clipboard_controller"
application.register("clipboard", ClipboardController)

import Compass3dController from "controllers/compass_3d_controller"
application.register("compass-3d", Compass3dController)

import DashboardController from "controllers/dashboard_controller"
application.register("dashboard", DashboardController)

import GaugeChartController from "controllers/gauge_chart_controller"
application.register("gauge-chart", GaugeChartController)

import GpsMapController from "controllers/gps_map_controller"
application.register("gps-map", GpsMapController)

import LineChartController from "controllers/line_chart_controller"
application.register("line-chart", LineChartController)

import ParticlesController from "controllers/particles_controller"
application.register("particles", ParticlesController)

import RevealController from "controllers/reveal_controller"
application.register("reveal", RevealController)

import ValueCardController from "controllers/value_card_controller"
application.register("value-card", ValueCardController)

import WidgetFormController from "controllers/widget_form_controller"
application.register("widget-form", WidgetFormController)

import LiveTelemetryController from "controllers/live_telemetry_controller"
application.register("live-telemetry", LiveTelemetryController)

import CameraFeedController from "controllers/camera_feed_controller"
application.register("camera-feed", CameraFeedController)
import TabsController from "controllers/tabs_controller"
application.register("tabs", TabsController)
