[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_protocol = esptool
upload_port  = /dev/cu.usbmodem14201
monitor_port = /dev/cu.usbmodem14201
lib_deps =
    electroniccats/MPU6050@^1.4.1
    mprograms/QMC5883LCompass@^1.2.3
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit Unified Sensor@^1.1.14
    mikalhart/TinyGPSPlus@^1.0.3
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
